USE UARK;

CREATE TABLE APP (
  ID          INT         NOT NULL AUTO_INCREMENT,
  TITLE       VARCHAR(20) NOT NULL,
  PUBLISHER   VARCHAR(20) NOT NULL,
  VERSION     FLOAT       NOT NULL,
  DESCRIPTION VARCHAR(200),
  CREATE_DATE TIMESTAMP   NOT NULL,
  PRIMARY KEY (ID)
);